force-app/main/default/objects/Panier__c/Panier__c.object-meta.xml
<CustomObject>
    <label>Panier</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paniers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panier__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Paniers</relationshipLabel>
    <relationshipName>Paniers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Panier__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()+1</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PRG_PanierExtension.cls
public class PRG_PanierExtension {
	private final Panier__c P;

    public List<Panier__c> getPaniers(){
        return [SELECT Name,Date__c,Compte__r.AccountNumber, Compte__r.Name,Compte__r.BillingStreet,Compte__r.BillingPostalCode,Compte__r.BillingCity,(SELECT Patient__c, Name,Praticien__r.FirstName, Praticien__r.LastName FROM Opportunit_s__r) from Panier__c where Date__c = :P.date__c];
    }
    
    public PRG_PanierExtension(ApexPages.StandardController stdController) { 
        this.P = (Panier__c)stdController.getRecord();
    }
}