force-app/main/default/objects/Panier__c/Panier__c.object-meta.xml
<CustomObject>
    <label>Panier</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paniers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panier__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A vérifier</fullName>
                <default>true</default>
                <label>A vérifier</label>
            </value>
            <value>
                <fullName>Vérif OK</fullName>
            </value>
            <value>
                <fullName>A expédier</fullName>
            </value>
            <value>
                <fullName>Expédié</fullName>
            </value>
            <value>
                <fullName>Livré</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRG_ScanPanier.cls
public with sharing class PRG_ScanPanier {

    @AuraEnabled
    public static string OppURL(string OppName,string PanierId) {
        List<Opportunity> Opps = [Select Id,panier__c,Verification_panier__c from Opportunity where Name =:OppName and Panier__c=:PanierId and StageName='En cours de vérification'];
        if (Opps.size() > 0){
            Opps[0].Verification_panier__c = !Opps[0].Verification_panier__c;
            update Opps[0];
            List<Opportunity> OppsPanier = [Select Id from Opportunity where panier__c=:PanierID and Verification_panier__c=false];
            if(OppsPanier.size()==0){
                Panier__c P = new Panier__c();
                P.Id = PanierId;
                P.Statut__c = 'Vérif OK';
                update P;
            }else{
                Panier__c P = new Panier__c();
                P.Id = PanierId;
                P.Statut__c = 'A vérifier';
                update P;
            }
            return '';
        }else{
            Opps = [Select Id,panier__c from Opportunity where Name =:OppName and StageName='En cours de vérification'];
            if(Opps.size()>0){
                return 'Opportunité non trouvée dans ce panier';
            }else{
                return 'Opportunité non trouvée';
            }
        }
    }
}