force-app/main/default/objects/Expedition__c/Expedition__c.object-meta.xml
<CustomObject>
    <label>Expédition</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expéditions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expedition__c/fields/Destinataire__c.field-meta.xml
<CustomField>
    <fullName>Destinataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destinataire</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expéditions</relationshipLabel>
    <relationshipName>Exp_ditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expedition__c/fields/Envoi_des_emails__c.field-meta.xml
<CustomField>
    <fullName>Envoi_des_emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Envoi des emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expedition__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En transit</fullName>
                <default>true</default>
                <label>En transit</label>
            </value>
            <value>
                <fullName>BAE</fullName>
            </value>
            <value>
                <fullName>Arrivée partielle</fullName>
            </value>
            <value>
                <fullName>Arrivée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>Lignes</relationshipLabel>
    <relationshipName>Lignes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/Ligne_de_commande__c.object-meta.xml
<CustomObject>
    <label>Ligne de commande</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de commande</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne_de_commande__c/fields/Ligne__c.field-meta.xml
<CustomField>
    <fullName>Ligne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne</label>
    <referenceTo>Ligne__c</referenceTo>
    <relationshipLabel>Lignes de commande</relationshipLabel>
    <relationshipName>Lignes_de_commande</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>Lignes de commande</relationshipLabel>
    <relationshipName>Lignes_de_commande</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordonnance__c/fields/Mode_de_livraison__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_livraison__c</fullName>
    <formula>TEXT(Dossier__r.Mode_de_livraison__c)</formula>
    <label>Mode de livraison</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>Envoyée au labo</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>En cours de fabrication</fullName>
            </value>
            <value>
                <fullName>En cours de vérification</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Reçue</fullName>
            </value>
            <value>
                <fullName>Rejetée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Panier__c/Panier__c.object-meta.xml
<CustomObject>
    <label>Panier</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paniers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Panier__c/fields/Date_d_exp_dition__c.field-meta.xml
<CustomField>
    <fullName>Date_d_exp_dition__c</fullName>
    <label>Date d&apos;expédition</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Panier__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A vérifier</fullName>
                <default>true</default>
                <label>A vérifier</label>
            </value>
            <value>
                <fullName>Vérif OK</fullName>
            </value>
            <value>
                <fullName>A expédier</fullName>
            </value>
            <value>
                <fullName>Expédié</fullName>
            </value>
            <value>
                <fullName>Livré</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retour__c/Retour__c.object-meta.xml
<CustomObject>
    <label>Retour</label>
    <nameField>
        <label>LAB#</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retour__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/Ligne__c.field-meta.xml
<CustomField>
    <fullName>Ligne__c</fullName>
    <label>Ligne</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/Quantite__c.field-meta.xml
<CustomField>
    <fullName>Quantite__c</fullName>
    <label>UNIT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PRG_Tests.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PRG_Tests {

    static testMethod void OppFlowTest1() {
      Map<String,ID> profiles = new Map<String,ID>();
      List<Profile> ps = [select id, name from Profile where name like 'Numerident%'];

      for(Profile p : ps){
         profiles.put(p.name, p.id);
      }
    
        UserRole Role = [Select Id from Userrole where DeveloperName='HQ'];
    
      User standard = new User(alias = 'standt', 
      email='standarduser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='fr', 
      localesidkey='fr', 
      profileid = profiles.get('Numerident Standard'), 
      timezonesidkey='Europe/Paris', 
      UserRoleId=Role.Id,
      username='standarduser@testorgnumerident.com');
      insert standard;  

      User admin = new User(alias = 'admin', 
      email='adminuser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='fr', 
      localesidkey='fr', 
      profileid = profiles.get('Numerident Admin'), 
      timezonesidkey='Europe/Paris', 
      UserRoleId=Role.Id,
      username='adminuser@testorgnumerident.com');
      insert admin; 
        
      User usine = new User(alias = 'usine', 
      email='usineuser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='en_US', 
      localesidkey='en_US', 
      profileid = profiles.get('Numerident Usine'), 
      timezonesidkey='America/Los_Angeles', 
      UserRoleId=Role.Id,
      username='usineuser@testorgnumerident.com');
      insert usine; 

        Opportunity Opp = new Opportunity();
    
    system.runas(admin){
        Id pricebookId = Test.getStandardPricebookId();
        
        Account Acc = new Account();
        Acc.NAme = 'Centre';
        insert Acc;
        
        Opp.AccountId = Acc.ID;
        Opp.CloseDate = date.today();
        Opp.Date_d_exp_dition__c = date.today().addDays(-10);
        Opp.StageName = 'Envoyé au laboratoire';
        Opp.Name = 'Test';
        Opp.PriceBook2ID = pricebookId;
        insert Opp;
    }
    
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Envoyé au laboratoire',Opp.StageName);
      }
      system.runas(admin){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de traitement',Opp.StageName);
      }
      
      system.runas(standard){
        Opp.StageName = 'Livré au client';
        update Opp;
      }
        
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Livré au client',Opp.StageName);
      }
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Livré au client',Opp.StageName);
        Opp.StageName = 'Facturé';
        update Opp;
      }
        
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Facturé',Opp.StageName);
      }
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Facturé',Opp.StageName);
        Opp.StageName = 'Réglé';
        update Opp;
      }
        
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Réglé',Opp.StageName);
      }
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Réglé',Opp.StageName);
        Opp.StageName = 'Rejeté';
        update Opp;
      }

      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Rejeté',Opp.StageName);
      }
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Rejeté',Opp.StageName);
      }

        
    }

    static testMethod void OppFlowTest2() {
      Map<String,ID> profiles = new Map<String,ID>();
      List<Profile> ps = [select id, name from Profile where name like 'Numerident%'];

      for(Profile p : ps){
         profiles.put(p.name, p.id);
      }
    
        UserRole Role = [Select Id from Userrole where DeveloperName='HQ'];
    
      User standard = new User(alias = 'standt', 
      email='standarduser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='fr', 
      localesidkey='fr', 
      profileid = profiles.get('Numerident Standard'), 
      timezonesidkey='Europe/Paris', 
      UserRoleId=Role.Id,
      username='standarduser@testorgnumerident.com');
      insert standard;  

      User admin = new User(alias = 'admin', 
      email='adminuser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='fr', 
      localesidkey='fr', 
      profileid = profiles.get('Numerident Admin'), 
      timezonesidkey='Europe/Paris', 
      UserRoleId=Role.Id,
      username='adminuser@testorgnumerident.com');
      insert admin; 
        
      User usine = new User(alias = 'usine', 
      email='usineuser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='en_US', 
      localesidkey='en_US', 
      profileid = profiles.get('Numerident Usine'), 
      timezonesidkey='America/Los_Angeles', 
      UserRoleId=Role.Id,
      username='usineuser@testorgnumerident.com');
      insert usine; 

        Opportunity Opp = new Opportunity();
    
    system.runas(admin){
        Id pricebookId = Test.getStandardPricebookId();
        
        Account Acc = new Account();
        Acc.NAme = 'Centre';
        insert Acc;
        
        Opp.AccountId = Acc.ID;
        Opp.CloseDate = date.today();
        Opp.Date_d_exp_dition__c = date.today().addDays(-10);
        Opp.StageName = 'Validé';
        Opp.Name = 'Test';
        Opp.PriceBook2ID = pricebookId;
        insert Opp;
    }
    
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Validé',Opp.StageName);
      }
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de traitement',Opp.StageName);
      }
      
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de traitement',Opp.StageName);
      }
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de traitement',Opp.StageName);
        Opp.StageName = 'En transit vers l\'usine';
        update Opp;
      }
      
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En transit vers l\'usine',Opp.StageName);
      }
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de fabrication',Opp.StageName);
      }

      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de fabrication',Opp.StageName);
      }
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En transit vers le labo',Opp.StageName);
      }
        
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de fabrication',Opp.StageName);
      }
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En transit vers le labo',Opp.StageName);
      }

    }

    static testMethod void OppFlowTest3() {
      Map<String,ID> profiles = new Map<String,ID>();
      List<Profile> ps = [select id, name from Profile where name like 'Numerident%'];

      for(Profile p : ps){
         profiles.put(p.name, p.id);
      }
    
        UserRole Role = [Select Id from Userrole where DeveloperName='HQ'];
    
      User standard = new User(alias = 'standt', 
      email='standarduser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='fr', 
      localesidkey='fr', 
      profileid = profiles.get('Numerident Standard'), 
      timezonesidkey='Europe/Paris', 
      UserRoleId=Role.Id,
      username='standarduser@testorgnumerident.com');
      insert standard;  

      User admin = new User(alias = 'admin', 
      email='adminuser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='fr', 
      localesidkey='fr', 
      profileid = profiles.get('Numerident Admin'), 
      timezonesidkey='Europe/Paris', 
      UserRoleId=Role.Id,
      username='adminuser@testorgnumerident.com');
      insert admin; 
        
      User usine = new User(alias = 'usine', 
      email='usineuser@testorgnumerident.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='en_US', 
      localesidkey='en_US', 
      profileid = profiles.get('Numerident Usine'), 
      timezonesidkey='America/Los_Angeles', 
      UserRoleId=Role.Id,
      username='usineuser@testorgnumerident.com');
      insert usine; 

        Opportunity Opp = new Opportunity();
    
    system.runas(admin){
        Id pricebookId = Test.getStandardPricebookId();
        
        Account Acc = new Account();
        Acc.NAme = 'Centre';
        insert Acc;
        
        Opp.AccountId = Acc.ID;
        Opp.CloseDate = date.today();
        Opp.Date_d_exp_dition__c = date.today().addDays(-10);
        Opp.StageName = 'En cours de fabrication';
        Opp.Name = 'Test';
        Opp.Mode_de_livraison__c = 'J+1';
        Opp.PriceBook2ID = pricebookId;
        insert Opp;
    }
    
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En transit vers le labo',Opp.StageName);
      }

      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de vérification',Opp.StageName);
      }
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('En cours de vérification',Opp.StageName);
          Panier__c P = new Panier__c();
          P.Name = 'Panier du jour';
          insert P;
      }
        
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Expédié',Opp.StageName);
      }
      system.runas(usine){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Expédié',Opp.StageName);
      }
        
      system.runas(standard){
        PRG_Scan.OppURL('Test');
        Opp = [Select Id,StageName from Opportunity where Id=:Opp.Id];
        System.assertEquals('Expédié',Opp.StageName);
      }
        
        
    }
    
    static testMethod void fullSimpleTest() {
        Product2 prod = new Product2(Name = 'Test', ProductCode = 'DIVERS');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;        

        Account Acc = new Account();
        Acc.NAme = 'Centre';
        insert Acc;
        
        Account Usine = new Account();
        Usine.Name = 'Usine';
        Usine.Type = 'Partner';
        insert Usine;
        
        Opportunity Opp = new Opportunity();
        Opp.AccountId = Acc.ID;
        Opp.Usine__c = Usine.ID;
        Opp.CloseDate = date.today();
        Opp.Date_d_exp_dition__c = date.today().addDays(-10);
        Opp.StageName = 'En cours de traitement';
        Opp.Name = 'Test';
        Opp.Mode_de_livraison__c = 'J+1';
        Opp.PriceBook2ID = pricebookId;
        insert Opp;

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = 5,
            PricebookEntryId = standardPrice.Id,
            TotalPrice = 5 * standardPrice.UnitPrice
        );
        insert oli;
        
        PRG_Scan.OppURL('Test');
        
        Expedition__c Exp = new Expedition__c();
        Exp.Destinataire__c = Usine.ID;
        insert Exp;
        
        Exp.Envoi_des_emails__c = true;
        update Exp;
        
        Retour__c Ret = new Retour__c();
        Ret.Name = 'Test';
        Ret.Code__c='CCM : Céramo-métallique';
        Ret.Quantite__c = 2;
        insert Ret;
        
        Opp.Statut_de_facturation__c = 'En préparation';
        update Opp;
        
        sofactoapp__Raison_Sociale__c RS = new sofactoapp__Raison_Sociale__c();
        RS.Name = 'Test';
        RS.sofactoapp__Credit_prefix__c = 'FC{!AAAA}';
        RS.sofactoapp__Invoice_prefix__c = 'AV{!AAAA}';
        insert RS;
        
        RS.D_but_de_p_riode__c = date.today();
        RS.Fin_de_p_riode__c = date.today();
        RS.Preparer_la_facturation__c = true;
        update RS;
        
        Ordonnance__c Ord = new Ordonnance__c();
        Ord.Name = 'Test';
        insert Ord;

		ContentVersion contentVersion = new ContentVersion(
  		Title = 'TESTS',
  		PathOnClient = 'TESTS.DCM',
  		VersionData = Blob.valueOf('Test Content'),
  		IsMajorVersion = true
		);
		insert contentVersion;    
		List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
		ContentDocumentLink cdl = New ContentDocumentLink();
		cdl.LinkedEntityId = Ord.id;
		cdl.ContentDocumentId = documents[0].Id;
		cdl.shareType = 'V';
		insert cdl;
        delete cdl;

        Ord.Statut__c = 'Envoyée au labo';
        update Ord;

        sofactoapp__Factures_Client__c Fac = new sofactoapp__Factures_Client__c();
        Fac.sofactoapp__Compte__c = Acc.Id;
        Fac.sofactoapp__emetteur_facture__c = RS.Id;
        insert Fac;

        Ligne_de_commande__c LC = new Ligne_de_commande__c();
        LC.Ordonnance__c = Ord.Id;
        insert LC;

        Ligne__c Li = new Ligne__c();
        Li.Ordonnance__c = Ord.Id;
        insert Li;
        
        Case C = new Case();
        C.AccountId = Acc.Id;
        insert C;
        
        PRG_Utils.Couverture();
        PRG_Utils.Couverture2();
        PRG_Utils.Couverture3();
        PRG_Utils.Couverture4();
        PRG_Utils.Couverture5();
        PRG_Utils.Couverture6();
    }
}