force-app/main/default/objects/Expedition__c/Expedition__c.object-meta.xml
<CustomObject>
    <label>Expédition</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expéditions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expedition__c/fields/Poids__c.field-meta.xml
<CustomField>
    <fullName>Poids__c</fullName>
    <label>Poids</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PRG_ProFormaController.cls
public class PRG_ProFormaController {
    private final Expedition__c Exp;
    public integer MontantUnitaire {get;set;}
    
    public PRG_ProFormaController(ApexPages.StandardController stdController) {
        this.Exp = (Expedition__c)stdController.getRecord();
        MontantUnitaire = (integer) math.ceil((23 / getnbDossiers())) ;
    }

    public List<Opportunity> getListeDossiers() {
    	return [Select Id,Name,Patient__c from Opportunity where Expedition__c = :Exp.Id order by Name];
    }
    public decimal getnbDossiers() {
    	List<Opportunity> Opps = [Select Id from Opportunity where Expedition__c = :Exp.Id];
    	return Opps.size();
    }
    public decimal getPoidsMoyen() {
    	List<Opportunity> Opps = [Select Id from Opportunity where Expedition__c = :Exp.Id];
    	if (Opps.size() == 0){
    		return 0;
    	}else{
	        return Exp.Poids__c / Opps.size();
    	}
    }    
}