force-app/main/default/objects/Ligne_de_commande__c/Ligne_de_commande__c.object-meta.xml
<CustomObject>
    <label>Ligne de commande</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de commande</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne_de_commande__c/fields/Comp0__c.field-meta.xml
<CustomField>
    <fullName>Comp0__c</fullName>
    <description>IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Inlay core&quot;)),TEXT(Ligne__r.Type__c) + &quot; &quot; + TEXT(Ligne__r.Alliage_Inlay_core__c) ,&quot;&quot;) +</description>
    <formula>IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Gouttière&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Ortho&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;PEI, Cire&quot;)), UPPER(Details__c),&quot;&quot;) + 
IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Couronne&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Planification implantaire&quot;)),TEXT( Ligne__r.Liaison__c ),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comp0</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Comp1__c.field-meta.xml
<CustomField>
    <fullName>Comp1__c</fullName>
    <description>IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Résine&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Stellite&quot;)),&quot; EXTRAIRE &quot;,&quot;&quot;) + 
IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Résine&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Stellite&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Inlay onlay facette&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Inlay core&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Projet esthétique&quot;)),Ligne__r.Liste_des_dents__c ,&quot;&quot;)</description>
    <formula>IF(  Ligne__r.RecordType.DeveloperName = &quot;Resine&quot;,&quot; EXTRAIRE &quot;,&quot;&quot;) + 
IF( OR(Ligne__r.RecordType.DeveloperName = &quot;Resine&quot;,ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Inlay onlay facette&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Inlay core&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Projet esthétique&quot;)),Ligne__r.Liste_des_dents__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comp1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Comp2__c.field-meta.xml
<CustomField>
    <fullName>Comp2__c</fullName>
    <description>IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Résine&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Stellite&quot;)),&quot; REMPLACER &quot;,&quot;&quot;) + 
IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Résine&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Stellite&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Couronne&quot;)), Ligne__r.Liste_des_dents_2__c ,&quot;&quot;)</description>
    <formula>IF( Ligne__r.RecordType.DeveloperName = &quot;Resine&quot;,&quot; REMPLACER &quot;,&quot;&quot;) + 
IF( OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Résine&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Stellite&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Couronne&quot;)), Ligne__r.Liste_des_dents_2__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comp2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Comp3__c.field-meta.xml
<CustomField>
    <fullName>Comp3__c</fullName>
    <formula>IF(OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Pilier&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Barre&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Planification implantaire&quot;)),Ligne__r.Liste_des_dents__c + &quot; &quot; +  TEXT(Ligne__r.Marque_d_implant__c)  + &quot; &quot; +  Ligne__r.R_f_rence_d_implant__c + &quot; &quot; +  Ligne__r.Diam_tre__c + &quot; &quot; +  Ligne__r.Type_d_empreinte_sur_implant__c,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comp3</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Comp4__c.field-meta.xml
<CustomField>
    <fullName>Comp4__c</fullName>
    <formula>IF(OR(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Couronne sur implant&quot;),ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Appareil&quot;)),Ligne__r.Liste_des_dents_2__c + &quot; &quot; + TEXT( Ligne__r.Liaison__c ) ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comp4</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Comp5__c.field-meta.xml
<CustomField>
    <fullName>Comp5__c</fullName>
    <formula>IF(ISPICKVAL( Business_case__r.Sous_cran__c ,&quot;Réparations&quot;),Ligne__r.Liste_des_dents_2__c + &quot; &quot; + TEXT( Ligne__r.Liaison__c )  + &quot; &quot; + TEXT( Ligne__r.Arcade__c ) ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comp5</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>Lignes de commande</relationshipLabel>
    <relationshipName>Lignes_de_commande</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Prefs_EN__c.field-meta.xml
<CustomField>
    <fullName>Prefs_EN__c</fullName>
    <label>Prefs (EN)</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <formula>Produit__r.Product_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lignes de commande</relationshipLabel>
    <relationshipName>Lignes_de_commande</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Travail__c.field-meta.xml
<CustomField>
    <fullName>Travail__c</fullName>
    <formula>Produit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Travail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/txtQuantite__c.field-meta.xml
<CustomField>
    <fullName>txtQuantite__c</fullName>
    <formula>TEXT( Quantite__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>txtQuantite</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Materiau__c/Materiau__c.object-meta.xml
<CustomObject>
    <label>Matériau</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matériaux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Materiau__c/fields/Num_ro_CE__c.field-meta.xml
<CustomField>
    <fullName>Num_ro_CE__c</fullName>
    <label>Numéro CE</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Materiau__c/fields/Num_ro_de_lot__c.field-meta.xml
<CustomField>
    <fullName>Num_ro_de_lot__c</fullName>
    <label>Numéro de lot</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Materiau__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <label>Produit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACRYLIC DENTURE</fullName>
            </value>
            <value>
                <fullName>CAST METAL COCR FRAMEWORK</fullName>
            </value>
            <value>
                <fullName>COMPOSITE</fullName>
            </value>
            <value>
                <fullName>EMAX</fullName>
            </value>
            <value>
                <fullName>EMAX CAD</fullName>
            </value>
            <value>
                <fullName>FLEXIBLE DENTURE</fullName>
            </value>
            <value>
                <fullName>FMC</fullName>
            </value>
            <value>
                <fullName>IMPLANT BAR</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>POST&amp;CORE</fullName>
            </value>
            <value>
                <fullName>ZIRCONIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Materiau__c/fields/Usine__c.field-meta.xml
<CustomField>
    <fullName>Usine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usine</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Matériaux</relationshipLabel>
    <relationshipName>Mat_riaux</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracabilite__c/Tracabilite__c.object-meta.xml
<CustomObject>
    <label>Tracabilité</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracabilité</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracabilite__c/fields/Materiau__c.field-meta.xml
<CustomField>
    <fullName>Materiau__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matériau</label>
    <referenceTo>Materiau__c</referenceTo>
    <relationshipLabel>Tracabilité</relationshipLabel>
    <relationshipName>Tracabilit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tracabilite__c/fields/Num_ro_de_lot__c.field-meta.xml
<CustomField>
    <fullName>Num_ro_de_lot__c</fullName>
    <label>Numéro de lot</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracabilite__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>Tracabilité</relationshipLabel>
    <relationshipName>Tracabilit</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tracabilite__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tracabilité</relationshipLabel>
    <relationshipName>Tracabilit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PRG_BonLivraison_Extension.cls
public without sharing class PRG_BonLivraison_Extension {
    private final Ordonnance__c Ord;
    public boolean ShowTrac {get;set;}
    public decimal PrixTotal {get;set;}
    
    public List<Ligne_de_commande__c> getLCs(){
        map<ID,decimal> mapPrice = new map<ID,decimal>();
        List<Id> LCIds = new List<Id>();
        List<Ligne_de_commande__c> LCs = [Select Id,Travail__c,Product_name__c,txtQuantite__c,Comp0__c,Comp1__c,Comp2__c,Comp3__c,
                                          Comp4__c,Comp5__c,Prefs_EN__c,TotalPrice__c from Ligne_de_commande__c 
                                          where Ordonnance__c=:Ord.Id];
        for(Ligne_de_commande__c LC:LCs){
            LCIds.Add(LC.ID);
        }
        List<OpportunityLineItem> OppLis = [Select Ligne_de_commande__c,TotalPrice from OpportunityLineItem where Ligne_de_commande__c in :LCIds];
        for(OpportunityLineItem OppLi:OppLis){
            mapPrice.put(OppLi.Ligne_de_commande__c,OppLi.TotalPrice);
        }
        PrixTotal = 0;
        for(Ligne_de_commande__c LC:LCs){
            if(mapPrice.containskey(LC.Id)){
                LC.TotalPrice__c = mapPrice.get(LC.Id);
                if(LC.TotalPrice__c!=null){
                    PrixTotal += LC.TotalPrice__c;
                }
            }
        }
        return Lcs;
    }
    
    public List<Tracabilite__c> getTracas(){
        List<Tracabilite__c> Ts = new List<Tracabilite__c>();
        List<Tracabilite__c> TOrd = [Select Id,Produit__r.Name,Materiau__r.Name,Materiau__r.Num_ro_CE__c,Num_ro_de_lot__c from Tracabilite__c where Ordonnance__c=:Ord.ID];
        map<string,string> mapTra = new map<string,string>();
        for(Tracabilite__c T:TOrd){
            if(!mapTra.containskey(T.Produit__r.Name+T.Materiau__r.Name+T.Materiau__r.Num_ro_CE__c+T.Num_ro_de_lot__c)){
                mapTra.put(T.Produit__r.Name+T.Materiau__r.Name+T.Materiau__r.Num_ro_CE__c+T.Num_ro_de_lot__c,null);
	            Ts.Add(T);
            }
        }
        return Ts;
    }

    public string getPaysFab(){
        string tmp = 'France';
        List<Opportunity> Opp = [Select Id,Usine__c,Usine__r.Pays_de_fabrication__c from Opportunity where Ordonnance__c=:Ord.Id];            
        if(Opp[0].Usine__c != null){
	        if(!string.isblank(Opp[0].Usine__r.Pays_de_fabrication__c)){
                tmp = Opp[0].Usine__r.Pays_de_fabrication__c;
    	    }
        }
        return tmp;
    }

    public PRG_BonLivraison_Extension(ApexPages.StandardController stdController) { 
        this.Ord = (Ordonnance__c)stdController.getRecord();
        List<Tracabilite__c> TOrd = [Select Id,Produit__r.Name,Materiau__r.Name,Materiau__r.Num_ro_CE__c,Num_ro_de_lot__c from Tracabilite__c where Ordonnance__c=:Ord.ID];
        ShowTrac = (TOrd.size()>0);
    }
}