force-app/main/default/objects/Scan_export__c/Scan_export__c.object-meta.xml
<CustomObject>
    <label>Scan export</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scans export</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scan_export__c/fields/CAB__c.field-meta.xml
<CustomField>
    <fullName>CAB__c</fullName>
    <label>CAB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRG_ScanExport_Test.cls
@isTest
private class PRG_ScanExport_Test {

    static testMethod void Test() {
        Account Acc = new Account();
        Acc.NAme = 'Centre';
        insert Acc;
        Opportunity Opp = new Opportunity();
        Opp.AccountId = Acc.ID;
        Opp.CloseDate = date.today();
        Opp.Date_d_exp_dition__c = date.today().addDays(-10);
        Opp.StageName = 'Validé';
        Opp.Name = 'Test';
        insert Opp;
        
        Scan_export__c S = new Scan_export__c();
      	S.CAB__c = 'Test';
      	insert S;

    }
}