force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Temp__c/Temp__c.object-meta.xml
<CustomObject>
    <label>Temp</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Temp__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <externalId>true</externalId>
    <label>Info</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Temp__c/fields/Valeur__c.field-meta.xml
<CustomField>
    <fullName>Valeur__c</fullName>
    <label>Valeur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SelectToothController.cls
public class SelectToothController {
    @AuraEnabled
    public static void saveTeeth(String teethValues, String recordId, String FieldId) {
        
/*        Ligne__c l = new Ligne__c();        
        String queryStr='SELECT Id,'+ FieldId + ' FROM Ligne__c WHERE Id = \'' + recordId + '\'';  
        List<Ligne__c> results=Database.query(queryStr);        
        l = results[0];    
        l.put( FieldId,'');
                
        Object[] values = (Object[])System.JSON.deserializeUntyped(teethValues);
        if(values.size()>0){
            l.put(FieldId,String.join(values, ';'));
        }
        
        update l; */
        Temp__c tmp = new Temp__c();
        tmp.Info__c = recordId + FieldId;
        tmp.Valeur__c = teethValues.replace('"",','');
        upsert tmp Info__c; 
    }
    
    @AuraEnabled
    public static String getTeeth(String recordId, String FieldId) {
        
        Ligne__c l = new Ligne__c();        
        String queryStr='SELECT Id,'+ FieldId + ' FROM Ligne__c WHERE Id = \'' + recordId + '\'';  
        List<Ligne__c> results=Database.query(queryStr);        
        l = results[0];    
        
        return (String)l.get(FieldId);
    }
}