force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne__c/fields/Extraction__c.field-meta.xml
<CustomField>
    <fullName>Extraction__c</fullName>
    <label>Extraction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ne rien extraire</fullName>
            </value>
            <value>
                <fullName>Extraire</fullName>
                <default>true</default>
                <label>Extraire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/hideArray.cls
public class hideArray

{
    private final Ligne__c ligne {get; set;}
    public boolean showComponent {get; set;}
    public Boolean SelectedVal {get; set;}
    
    public hideArray(ApexPages.StandardController ctrl)
    {
        //(Ligne__c)ctrl.getRecord()
        ligne = [SELECT Id, Extraction__c FROM Ligne__c WHERE Id = :ctrl.getRecord().Id];
        system.debug('extraction == '+ligne);
        if(ligne.Extraction__c == 'Extraire'){
        	showComponent = true ;

        }
        if(ligne.Extraction__c == 'Ne rien extraire'){
            SelectedVal = true ;
        }
    }
    
    public void RenderSec()
    {
        if(SelectedVal == false)
        {
            showComponent = true ;
            ligne.Extraction__c = 'Extraire';
            update ligne;
        }
        if(SelectedVal == true)
        {
            showComponent = false ; 
            ligne.Extraction__c = 'Ne rien extraire';
            update ligne;       }
        //return null ;
    }
}