force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne__c/fields/Couronne__c.field-meta.xml
<CustomField>
    <fullName>Couronne__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Couronne_sur_implants&quot;,&quot;CCM : Céramo-métallique&quot;,&quot;Inlay_core_couronne&quot;,&quot;CCM : Céramo-métallique&quot;,&quot;&quot;)</defaultValue>
    <label>Couronne</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Couronne</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Technical_Comments__c.field-meta.xml
<CustomField>
    <fullName>Technical_Comments__c</fullName>
    <label>Technical Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Facette&quot;,&quot;Céramique monolithique (hors zircone)&quot;,&quot;Inlay_core_couronne&quot;,&quot;Classique&quot;,&quot;Inlay_onlay&quot;,&quot;Composite&quot;,&quot;Resine&quot;,&quot;Résine standard&quot;,&quot;Wax_up&quot;,&quot;Wax-up&quot;,&quot;ResineSansAffectation&quot;,&quot;Résine standard&quot;,&quot;Planification_implantaire&quot;,&quot;Simplifié (pilot drill)&quot;,&quot;&quot;)</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TypeMassUpdateTest.cls
@isTest(seealldata = true)
public class TypeMassUpdateTest{
    static testMethod void testMassUpdateRecord() {
        Test.startTest();
        List<Ligne__c> LigneList = [SELECT ID, Couronne__c , Type__c , Technical_Comments__c FROM Ligne__c WHERE Type__c ='CCM' OR Type__c = 'EMAX' OR Type__c ='CCZ' OR Type__c ='Full Zr Multilayer' OR Type__c='Céramo-métallique' OR Type__c ='Céramique monolithique (hors zircone)' OR Type__c='Céramo-céramique ' OR Type__c='Céramique monolithique Zircone' LIMIT 10];
        TypeMassUpdate mr = new TypeMassUpdate();
        mr.errId = 'Test';
        Test.stopTest();
        Database.executeBatch(mr);

    }
}