force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne__c/fields/Couronne__c.field-meta.xml
<CustomField>
    <fullName>Couronne__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Couronne_sur_implants&quot;,&quot;CCM : Céramo-métallique&quot;,&quot;Inlay_core_couronne&quot;,&quot;CCM : Céramo-métallique&quot;,&quot;&quot;)</defaultValue>
    <label>Couronne</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Couronne</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Technical_Comments__c.field-meta.xml
<CustomField>
    <fullName>Technical_Comments__c</fullName>
    <label>Technical Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MassUpdateRecordTest.cls
@isTest(seealldata = true)
public class MassUpdateRecordTest {
    static testMethod void testMassUpdateRecord() {
		Test.startTest();
            List<Ligne__c> LigneList = [SELECT ID, Couronne__c , Technical_Comments__c FROM Ligne__c WHERE Couronne__c ='CCM' OR Couronne__c = 'EMAX' OR Couronne__c ='CCZ' OR Couronne__c ='Full Zr Multilayer' OR Couronne__c='Céramo-métallique' OR Couronne__c ='Céramique monolithique (hors zircone)' OR Couronne__c='Céramo-céramique' OR Couronne__c='Céramique monolithique Zircone' LIMIT 10];
            MassUpdateRecord mr = new MassUpdateRecord();
            mr.errId = 'Test';
        Test.stopTest();
        Database.executeBatch(mr);
    }
}