force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne__c/fields/Extraction__c.field-meta.xml
<CustomField>
    <fullName>Extraction__c</fullName>
    <label>Extraction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ne rien extraire</fullName>
            </value>
            <value>
                <fullName>Extraire</fullName>
                <default>true</default>
                <label>Extraire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>Lignes</relationshipLabel>
    <relationshipName>Lignes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ligne__c/recordTypes/Planification_implantaire.recordType-meta.xml
<RecordType>
    <fullName>Planification_implantaire</fullName>
    <active>true</active>
    <description>Après avoir enregistré la ligne, ne pas oublier de joindre le fichier CBCT à votre commande</description>
    <label>Planification implantaire (sur empreinte numérique)</label>
</RecordType>

force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/buttonNewLineController.cls
public class buttonNewLineController {
    @AuraEnabled
    Public Static List<recordtype> getRecordType () {
    	List<RecordType> rt;
    	string s = UserInfo.getUserId();
    	//if((s.startswith('0050Y000002EnVY'))||(s.startswith('0050Y000004cIc1'))||(s.startswith('0050Y000002rA1m'))||(s.startswith('0051v000004ewke'))){
    		rt =[select id, name from recordtype where SobjectType = 'ligne__c' and isActive=true];
    	//}else{
	    //    rt =[select id, name from recordtype where SobjectType = 'ligne__c' and developerName != 'Planification_implantaire' and isActive=true];
    	//}
        return rt;
    }

    @AuraEnabled
    Public Static Id createLigne(Id recordId, Id recordType) {
		System.debug('### Entering in createRecord');
        Ligne__c li = new Ligne__c();
        li.Ordonnance__c = recordId;
		li.RecordTypeId = recordType;
        li.Extraction__c = 'Extraire';
        insert li;
        
        return li.Id;
        
    }
}