force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne__c/fields/Alliage__c.field-meta.xml
<CustomField>
    <fullName>Alliage__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Couronne_sur_implants&quot;,&quot;CoCr&quot;,&quot;Inlay_core_couronne&quot;,&quot;CoCr&quot;,&quot;&quot;)</defaultValue>
    <label>Alliage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Couronne__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Alliages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Alliage_Inlay_core__c.field-meta.xml
<CustomField>
    <fullName>Alliage_Inlay_core__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Inlay_core_couronne&quot;,&quot;CoCr&quot;,&quot;&quot;)</defaultValue>
    <label>Alliage Inlay core</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Alliages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Arcade__c.field-meta.xml
<CustomField>
    <fullName>Arcade__c</fullName>
    <label>Arcade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Haut</fullName>
            </value>
            <value>
                <fullName>Bas</fullName>
            </value>
            <value>
                <fullName>Haut et bas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Couronne__c.field-meta.xml
<CustomField>
    <fullName>Couronne__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Couronne_sur_implants&quot;,&quot;CCM : Céramo-métallique&quot;,&quot;Inlay_core_couronne&quot;,&quot;CCM : Céramo-métallique&quot;,&quot;&quot;)</defaultValue>
    <label>Couronne</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Couronne</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Finition__c.field-meta.xml
<CustomField>
    <fullName>Finition__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Facette&quot;,&quot;Finition directe&quot;,&quot;Inlay_core_couronne&quot;,&quot;Finition directe&quot;,&quot;Stellite&quot;,&quot;Finition directe&quot;,&quot;Resine&quot;,&quot;Finition directe&quot;,&quot;Inlay_onlay&quot;,&quot;Finition directe&quot;,&quot;ResineSansAffectation&quot;,&quot;Finition directe&quot;,&quot;Planification_implantaire&quot;,&quot;Planification implantaire et impression du guide&quot;,&quot;&quot;)</defaultValue>
    <label>Finition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Finition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Liaison__c.field-meta.xml
<CustomField>
    <fullName>Liaison__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Inlay_core_couronne&quot;,&quot;Unitaire&quot;,&quot;Resine&quot;,&quot;Résine standard&quot;,&quot;Planification_implantaire&quot;,&quot;Dentaire&quot;,&quot;&quot;)</defaultValue>
    <label>Liaison</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unitaire</fullName>
            </value>
            <value>
                <fullName>Solidarisé</fullName>
            </value>
            <value>
                <fullName>Bridge</fullName>
            </value>
            <value>
                <fullName>Appui dentaire</fullName>
            </value>
            <value>
                <fullName>Résine standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <label>Produit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Produit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Facette&quot;,&quot;Céramique monolithique (hors zircone)&quot;,&quot;Inlay_core_couronne&quot;,&quot;Classique&quot;,&quot;Inlay_onlay&quot;,&quot;Composite&quot;,&quot;Resine&quot;,&quot;Résine standard&quot;,&quot;Wax_up&quot;,&quot;Wax-up&quot;,&quot;ResineSansAffectation&quot;,&quot;Résine standard&quot;,&quot;Planification_implantaire&quot;,&quot;Simplifié (pilot drill)&quot;,&quot;&quot;)</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/recordTypes/Services.recordType-meta.xml
<RecordType>
    <fullName>Services</fullName>
    <active>true</active>
    <label>Réparations</label>
</RecordType>

force-app/main/default/classes/champsLightning.cls
public class champsLightning {
    @AuraEnabled
    public static String getField(String recordId, String FieldId) {
       
        Ligne__c l = new Ligne__c();        
        String queryStr='SELECT Id,'+ FieldId + ' FROM Ligne__c WHERE Id = \'' + recordId + '\''; 
        List<Ligne__c> results=Database.query(queryStr);
               
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        
        String endpoint = URL.getSalesforceBaseUrl().toExternalForm() +
        '/services/data/v41.0/ui-api/object-info/Ligne__c/picklist-values/0125E00000010IeQAI/'+FieldId+'/';
            
        req.setEndpoint(endpoint);
        req.setMethod('GET');
        req.setHeader('Content-Type', 'application/json');
        if(!Test.isRunningTest())
            req.setHeader('Authorization', 'OAuth ' + PRG_Utils.getSessionIdFromVFPage(Page.SessionID));
        else
           req.setHeader('Authorization', 'OAuth SESSION ID');
        
        HttpResponse res = null;
        try{
            res = h.send(req);
            String response = res.getBody();
            System.debug('response '+response);
            return null;

        }
        catch(Exception e){
            System.debug('Error '+e.getMessage());
            
             return null;
        }
        
       // return (String)l.get(FieldId);
    }


   /* public class JSON2Apex {
	@AuraEnabled
		public  JSON2Apex {
		public ControllerValues controllerValues;
		public Object defaultValue;
		public String url;
		public List<Values> values;
		}

		public  Values {
		public Object attributes;
		public String label;
		public List<ControllerValues> validFor;
		public String value;
		}

		public  ControllerValues {
		}

	
		public static JSON2Apex parse(String json) {
		return (JSON2Apex) System.JSON.deserialize(json, JSON2Apex.class);
		}
} */

    @AuraEnabled
    public static void savefield(String fieldvalue, String recordId, String FieldId) {
        
        Ligne__c fi = new Ligne__c();        
        String queryStr='SELECT Id,'+ FieldId + ' FROM Ligne__c WHERE Id = \'' + recordId + '\'';  
        List<Ligne__c> results=Database.query(queryStr);        
        fi = results[0];    
        fi.put( FieldId,'');
        fi.put(FieldId,fieldvalue);
             
               /*
        Object[] values = (Object[])System.JSON.deserializeUntyped(fieldvalues);
        if(values.size()>0){
            );
        }
        */
        update fi;
    }
    
    @AuraEnabled
    public static List<String> getPicklistValues(String FieldName){
        
        List<String> results = new List<String>();
        
        if(FieldName == 'Finition__c'){
            Schema.DescribeFieldResult res = Ligne__c.Finition__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
                
            }  
        }
        if(FieldName == 'Produit__c'){
            if('Type__c' != 'none'){
            Schema.DescribeFieldResult res = Ligne__c.Produit__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
            else{
               // Ligne__c.Produit__c == 'none';
            }
        }
        if(FieldName == 'Alliage_Inlay_core__c'){
            Schema.DescribeFieldResult res = Ligne__c.Alliage_Inlay_core__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
        if(FieldName == 'Liaison__c'){
            Schema.DescribeFieldResult res = Ligne__c.Liaison__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
        if(FieldName == 'Arcade__c'){
            Schema.DescribeFieldResult res = Ligne__c.Arcade__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
        if(FieldName == 'Alliage__c'){
            if('Couronne__c' != 'none'){
            Schema.DescribeFieldResult res = Ligne__c.Alliage__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
        }
        if(FieldName == 'Couronne__c'){
            if('Type__c' != 'none'){
            Schema.DescribeFieldResult res = Ligne__c.Couronne__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
        }
        if(FieldName == 'Type__c'){
            Schema.DescribeFieldResult res = Ligne__c.Type__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
        if(FieldName == 'Options__c'){
            Schema.DescribeFieldResult res = Ligne__c.Options__c.getDescribe();            
            List<Schema.PicklistEntry> ple = res.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                results.add(pickListVal.getLabel());
            }  
        }
        
        
        return results;
    }
}