force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retour__c/Retour__c.object-meta.xml
<CustomObject>
    <label>Retour</label>
    <nameField>
        <label>LAB#</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retour__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>DESCRIPTION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/Full_match__c.field-meta.xml
<CustomField>
    <fullName>Full_match__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Full match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/IdPoste__c.field-meta.xml
<CustomField>
    <fullName>IdPoste__c</fullName>
    <label>IdPoste</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/Ligne__c.field-meta.xml
<CustomField>
    <fullName>Ligne__c</fullName>
    <label>Ligne</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/Manually_checked__c.field-meta.xml
<CustomField>
    <fullName>Manually_checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manually checked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retour__c/fields/Quantite__c.field-meta.xml
<CustomField>
    <fullName>Quantite__c</fullName>
    <label>UNIT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PRG_AnalyseRetour.cls
public class PRG_AnalyseRetour{
    public List<Retour__c> Rs {get;set;}
    public List<OpportunityLineItem> Os {get;set;}
	public List<clsRetour> anl {get;set;}
    public string str {get;set;}
    public integer nbTotal {get;set;}
    public integer nbOK {get;set;}
    public Opportunity Opp {get;set;}
    public List<Opportunity> Opps;
    public integer idx {get;set;}
    
    public class clsRetour{
        public Retour__c R {get;set;}
        public List<OpportunityLineItem> Os {get;set;}
        public List<string> Cs {get;set;}
        public string C {get;set;}
        public clsRetour(Retour__c pR,List<OpportunityLineItem> pOs){
            R = pR;
            Cs=new List<string>();
            Os = new List<OpportunityLineItem>();
            boolean Red;
            for(OpportunityLineItem pO:pOs){
                string couleur='#FFFFFF';
                Red=true;
                if(pR.IdPoste__c == (string)pO.ID){
                if((pR.Full_match__c)||(pR.Manually_checked__c)){
                    couleur = '#00FF00';
                    red=false;
                    pO.StyleRetour__c = '#00FF00';
                }else{
                    if(pR.Match__c){
                        couleur = '#FFCC00';
                        red=false;
                		pO.StyleRetour__c = '#FFCC00';
                    }else{
                        couleur = '#FFFFFF';
                        pO.StyleRetour__c = '#FFFFFF';
                    }
                }
                }else{
                    pO.StyleRetour__c = '#FFFFFF';
                }
                Cs.Add(pO.StyleRetour__c);
                Os.Add(pO);	
            }
 //           if (Red){
 //               C='#FF0000';
 //           }else{
                C='#FFFFFF';
 //           }
        }
    }
    
    public PRG_AnalyseRetour(){
		Opps = [Select Id,Name,Retours_OK__c from Opportunity where StageName='En cours de vérification'];
        nbTotal = Opps.size();
        nbOK = 0;
        if(nbTotal>0){
            idx = 0;
             OppCourante(Opps[idx]);
        }
    }
    
    public PageReference SaveNext(){
        if(!Opps[idx].Retours_OK__c){
	        Opps[idx].Retours_OK__c = true;
    	    nbOK++;
        }
        if(nbOK<nbTotal){
	        return Next();
        }else{
            return null;
        }
    }

    public PageReference Next(){
        idx++;
        if(idx==nbTotal){
            idx=0;
        }
        if(OppCourante(Opps[idx])){
			SaveNext();
	        return null;
        }else{
	        return null;
        }
    }
    public PageReference Prev(){
        idx--;
        if(idx==-1){
            idx=nbTotal-1;
        }
        OppCourante(Opps[idx]);
        return null;
    }

    
    public boolean OppCourante(Opportunity O){
        //str =apexpages.currentpage().getparameters().get('name');
        Opp = O;
        Rs = [Select Ligne__c,Code__c,Full_match__c,IdPoste__c,Name,Manually_checked__c,Match__c,Quantite__c 
              from Retour__c where Name=:O.Name];
        Os = [Select Opportunity.Name,Product2.Name,Id,Quantity,Name,StyleRetour__c from OpportunityLineItem 
              where Opportunity.Id=:O.Id];
        anl = new List<clsRetour>();
        for (Retour__c R:Rs){
            anl.add(new clsRetour(R,Os));
        }
        if((anl.size()==0)||(O.Retours_OK__c)){
            return true;
        }else{
            return false;
        }
    }
}