force-app/main/default/objects/Mirror__c/Mirror__c.object-meta.xml
<CustomObject>
    <label>Mirror</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mirrors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mirror__c/fields/LineId__c.field-meta.xml
<CustomField>
    <fullName>LineId__c</fullName>
    <externalId>true</externalId>
    <label>LineId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mirror__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Lines</relationshipLabel>
    <relationshipName>Mirrors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PRG_Mirroring.cls
public with sharing class PRG_Mirroring {
	@future
    public static void MirrorOppLineItems(list<Id> OppLiIds){
    	List<OpportunityLineItem> OppLis = [Select Id,OpportunityId,Quantity,Product2.Product_Name__c,Product2.Name,Description 
    										from OpportunityLineItem where Id in :OppLiIds];
    	List<Mirror__c> Ms = new List<Mirror__c>();
    	for(OpportunityLineItem OppLi:OppLis){
    		Mirror__c M = new Mirror__c();
    		M.LineId__c = OppLi.Id;
    		if(!string.isblank(OppLi.Product2.Product_Name__c)){
	    		M.Name = OppLi.Product2.Product_Name__c;
    		}else{
    			M.Name = OppLi.Product2.Name;
    		}
    		M.Description__c = OppLi.Description;
    		M.Opportunite__c = OppLi.OpportunityId;
    		M.Quantity__c = OppLi.Quantity;
    		MS.Add(M);
    	}
    	if(Ms.size()>0){
    		upsert Ms LineId__c;
    	}
    }
	@future
    public static void DeleteOppLineItems(list<Id> OppLiIds){
    	try{
    		List<Mirror__c> Ms = [Select Id from Mirror__c where LineId__c in :OppLiIds];
    		if (Ms.size() > 0){
	    		delete Ms;
    		}
    	}
    	catch (exception e){
    	}
    }
}