force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordonnance__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>Envoyée au labo</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>En cours de fabrication</fullName>
            </value>
            <value>
                <fullName>En cours de vérification</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Reçue</fullName>
            </value>
            <value>
                <fullName>Rejetée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PRG_Graph.cls
public with sharing class PRG_Graph {

    public List<WedgeData> getCaseData() {
        List<WedgeData> data = new List<WedgeData>();
        List<AggregateResult> Aggs = [Select count(Id) Nb,Priority from Case where isClosed = false group by Priority];
        for (AggregateResult Agg:Aggs){
	        data.add(new WedgeData((string)Agg.get('Priority'), (integer)Agg.Get('Nb')));
        }
        return data;
    }

    public List<WedgeData> getOrdonnanceData() {
        List<WedgeData> data = new List<WedgeData>();
        List<AggregateResult> Aggs = [Select count(Id) Nb,Statut__c from Ordonnance__c group by Statut__c];
        for (AggregateResult Agg:Aggs){
	        data.add(new WedgeData((string)Agg.get('Statut__c'), (integer)Agg.Get('Nb')));
        }
        return data;
    }

    // Wrapper class
    public class WedgeData {

        public String name { get; set; }
        public Integer data { get; set; }

        public WedgeData(String name, Integer data) {
            if(string.isblank(name)){
            	this.name = '-';	
            }else{
            	this.name = name;
            }
            this.data = data;
        }
    }
}