force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordonnance__c/fields/Choice_of_rating__c.field-meta.xml
<CustomField>
    <fullName>Choice_of_rating__c</fullName>
    <label>Choice of rating</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adaptation</fullName>
            </value>
            <value>
                <fullName>Teinte</fullName>
            </value>
            <value>
                <fullName>Occlusion</fullName>
            </value>
            <value>
                <fullName>Esthétique</fullName>
            </value>
            <value>
                <fullName>Délai non respecté</fullName>
            </value>
            <value>
                <fullName>Instruction non prise en compte</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ordonnance__c/fields/Choice_of_rating_other__c.field-meta.xml
<CustomField>
    <fullName>Choice_of_rating_other__c</fullName>
    <label>Choice of rating other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>Envoyée au labo</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>En cours de fabrication</fullName>
            </value>
            <value>
                <fullName>En cours de vérification</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Reçue</fullName>
            </value>
            <value>
                <fullName>Rejetée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_Ordonnance.cls
public class AP01_Ordonnance {
    @AuraEnabled
    public static Boolean updateOrdonnanceAboutRating(String ordonnanceId, Decimal rate, Decimal maxRate){
        Ordonnance__c objOrdonnance = [SELECT ID, Rating__c FROM Ordonnance__c WHERE Id =:ordonnanceId];
        if (rate < 0 && rate > maxRate) {
            System.debug('Il faut un rate entre 0 et ' + maxRate);
            return false;
        }
      	objOrdonnance.Rating__c = rate;
        try {
            update objOrdonnance;
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            return false;
        }
        return true;
    }
    
    @AuraEnabled
    public static Boolean updateOrdonnanceAboutChoiceOfRating(String ordonnanceId, String choices, String other){
        Ordonnance__c objOrdonnance = [SELECT ID, Choice_of_rating_other__c, Choice_of_rating__c FROM Ordonnance__c WHERE Id =:ordonnanceId];
        objOrdonnance.choice_of_rating__c = choices;
        
        if (other != null && other != '') {
            objOrdonnance.Choice_of_rating_other__c = other;
        }
  
        try {
            update objOrdonnance;
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            return false;
        }
        return true;
    }
    
    @AuraEnabled(cacheable=true) 
    public static Ordonnance__c getRatingById(String ordonnanceId){
    	Ordonnance__c objOrdonnance = [SELECT ID, Rating__c, Statut__c FROM Ordonnance__c WHERE Id =:ordonnanceId];
        System.debug(objOrdonnance);
        return objOrdonnance;
    }
    
    @AuraEnabled(cacheable=true)
    public static String getChoiceById(String ordonnanceId){
        Ordonnance__c objOrdonnance = [SELECT ID, Choice_of_rating__c FROM Ordonnance__c WHERE Id =:ordonnanceId];
        return objOrdonnance.Choice_of_rating__c;
    }
}