force-app/main/default/objects/Notation__c/Notation__c.object-meta.xml
<CustomObject>
    <description>Objet de notation grâce à un système d&apos;étoiles</description>
    <label>Notation</label>
    <nameField>
        <label>Notez la prestation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notation__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notation__c/fields/Objet_lie__c.field-meta.xml
<CustomField>
    <fullName>Objet_lie__c</fullName>
    <externalId>true</externalId>
    <label>Objet lié</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notation__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CtrlStarRating.cls
public class CtrlStarRating {
    
     @AuraEnabled
    public static Notation__c initData(string monid) {           
        //Notation__c  note=[SELECT Id, Name, Note__c, Commentaire__c, Objet_lie__c FROM Notation__c WHERE Objet_lie__c = :monid];
        //return note;
        List<Notation__c> Notes = [SELECT Id, Name, Note__c, Commentaire__c, Objet_lie__c FROM Notation__c WHERE Objet_lie__c = :monid];
        if (Notes.size()>0){
            return Notes[0];
        }else{
            Notation__c  note = new Notation__c  ();
            note.Objet_lie__c = monid;
            note.Ordonnance__c  = monid;
            note.Note__c = 5;
            return note;
        }
    }
     @AuraEnabled
    public static void UpdateData(Notation__c  MaNotation ,string newvalue) { 
        MaNotation.Note__c =  Decimal.valueOf(String.valueOf(newvalue));
       UPDATE  MaNotation;
    }
     @AuraEnabled
    public static Notation__c InsertData(string  idObj ,string newvalue) {
        Notation__c n = new Notation__c();
        n.Objet_lie__c = idObj;
        n.Ordonnance__c = idObj;
        n.Note__c =  Decimal.valueOf (String.valueOf(newvalue));
       UPSERT  n;
        return [SELECT Id, Name, Note__c, Commentaire__c, Objet_lie__c FROM Notation__c WHERE id = :n.id];
    }

}