force-app/main/default/objects/MyDocsFile__c/MyDocsFile__c.object-meta.xml
<CustomObject>
    <label>MyDocs File</label>
    <nameField>
        <label>MyDocs file</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyDocs Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MyDocsFile__c/fields/ContentSize__c.field-meta.xml
<CustomField>
    <fullName>ContentSize__c</fullName>
    <label>ContentSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyDocsFile__c/fields/FileExtension__c.field-meta.xml
<CustomField>
    <fullName>FileExtension__c</fullName>
    <label>Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyDocsFile__c/fields/FileUrl__c.field-meta.xml
<CustomField>
    <fullName>FileUrl__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>File Url</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MyDocsFile__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MyDocs Files</relationshipLabel>
    <relationshipName>MyDocsFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyDocsFile__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>MyDocs Files</relationshipLabel>
    <relationshipName>MyDocsFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordonnance__c/fields/Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dossier</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ordonnances</relationshipLabel>
    <relationshipName>Ordonnances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>Envoyée au labo</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>En cours de fabrication</fullName>
            </value>
            <value>
                <fullName>En cours de vérification</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Reçue</fullName>
            </value>
            <value>
                <fullName>Rejetée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ordonnance__c/recordTypes/Brouillon.recordType-meta.xml
<RecordType>
    <fullName>Brouillon</fullName>
    <active>true</active>
    <label>Brouillon</label>
</RecordType>

force-app/main/default/classes/MyDocsFileController.cls
public without sharing class MyDocsFileController {

    @AuraEnabled
    public static Id createRecord(String fileName, Integer contentSize, String fileUrl, String fileExt, String recordId){
        try{
            MyDocsFile__c file = new MyDocsFile__c(
                ContentSize__c=contentSize, 
                FileExtension__c=fileExt,
                FileName__c=fileName,
                FileUrl__c=fileUrl
            );
            if(recordId.startsWith('006')){
                Opportunity opp = [SELECT Id, Ordonnance__c FROM Opportunity WHERE Id = :recordId];
                file.Opportunity__c=opp.Id;
                // file.Ordonnance__c=opp.Ordonnance__c;
            }
            else{
                Ordonnance__c ord = [SELECT Id, Dossier__c FROM Ordonnance__c WHERE Id = :recordId];
                file.Ordonnance__c=ord.Id;
                file.Opportunity__c=ord.Dossier__c;
            }
            insert file;
            return file.Id;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean isEditable(String recordId) {
        if(recordId.startsWith('a0i')){
            List<Ordonnance__c> ords = [SELECT Id, Statut__c FROM Ordonnance__c WHERE Id = :recordId];
            System.debug('Size: '+ords.size());
            System.debug('Status: '+ords.get(0).Statut__c);
            if(ords.size() > 0 && ords.get(0).Statut__c != 'Brouillon'){
                System.debug('Not editable');
                return false;
            }
        }
        return true;   
    }

    @AuraEnabled
    public static AWS_Setting__mdt getAwsSetting(){
        List<AWS_Setting__mdt> settings = AWS_Setting__mdt.getAll().values();
        if(settings.size() > 0){
            return settings[0];
        }
        return null;
    }

    @AuraEnabled
    public static MyDocsFile__c getRecord(String recordId){
        MyDocsFile__c record = [SELECT Id, FileName__c, FileUrl__c, Name FROM MyDocsFile__c WHERE Id = :recordId LIMIT 1];
        return record;
    }

    public class MyDocsS3Exception extends Exception {}
}