force-app/main/default/objects/MyDocsFile__c/MyDocsFile__c.object-meta.xml
<CustomObject>
    <label>MyDocs File</label>
    <nameField>
        <label>MyDocs file</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyDocs Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MyDocsFile__c/fields/Ordonnance__c.field-meta.xml
<CustomField>
    <fullName>Ordonnance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordonnance</label>
    <referenceTo>Ordonnance__c</referenceTo>
    <relationshipLabel>MyDocs Files</relationshipLabel>
    <relationshipName>MyDocsFiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/Ordonnance__c.object-meta.xml
<CustomObject>
    <label>Ordonnance</label>
    <nameField>
        <label>Numero</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ordonnances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordonnance__c/fields/Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dossier</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ordonnances</relationshipLabel>
    <relationshipName>Ordonnances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordonnance__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>Envoyée au labo</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>En cours de fabrication</fullName>
            </value>
            <value>
                <fullName>En cours de vérification</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Reçue</fullName>
            </value>
            <value>
                <fullName>Rejetée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ordonnance__c/recordTypes/Brouillon.recordType-meta.xml
<RecordType>
    <fullName>Brouillon</fullName>
    <active>true</active>
    <label>Brouillon</label>
</RecordType>

force-app/main/default/classes/MyDocsFileController_TEST.cls
@isTest
class MyDocsFileController_TEST {

    @testSetup 
    static void setup() {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Fabriquant').getRecordTypeId();
        Account acc = new Account(
            Name = 'TEST UNIT 1',
            recordTypeId = recordTypeId,
            Zone_de_livraison__c = 'Paris'
        );
        insert acc;
        // Opp
        Opportunity opp = new Opportunity(
            Name ='Test UNIT',
            AccountID = acc.ID,
            StageName = 'Customer Won',
            Amount = 3000,
            CloseDate = System.today()
        );
        insert opp; 
        // ordonnance Brouillon
        Ordonnance__c ord = new Ordonnance__c(
            Dossier__c = opp.Id,
            Statut__c = 'Brouillon'
        );
        insert ord;
        // Ordonnance Validée      
        Ordonnance__c ordValid = new Ordonnance__c(
            Dossier__c = opp.Id,
            Statut__c = 'Validée'
        );
        insert ordValid;
    }
    
    @isTest 
    static void TestCreateOppFile(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test UNIT'];
        Ordonnance__c ord = [SELECT Id FROM Ordonnance__c WHERE Dossier__c = :opp.Id AND Statut__c = 'Brouillon'];

        Id fileOrdoId = MyDocsFileController.createRecord('TEST', 1000, 'testURL', '.txt', ord.id);
        System.assertNotEquals(null, fileOrdoId);
        Id fileId = MyDocsFileController.createRecord('TEST Opp', 1000, 'testURL2', '.txt', opp.id);
        System.assertNotEquals(null, fileId);
        
        MyDocsFile__c file = MyDocsFileController.getRecord(fileId);
        System.assertEquals(fileId, file.Id);
    }
    
    @isTest 
    static void TestIsEditable(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test UNIT'];
        Ordonnance__c ord = [SELECT Id FROM Ordonnance__c WHERE Dossier__c = :opp.Id AND Statut__c = 'Brouillon'];
        Ordonnance__c ordValide = [SELECT Id FROM Ordonnance__c WHERE Dossier__c = :opp.Id AND Statut__c = 'Validée'];

        System.assertEquals(true, MyDocsFileController.isEditable(opp.Id));
        System.assertEquals(true, MyDocsFileController.isEditable(ord.Id));
        System.assertEquals(false, MyDocsFileController.isEditable(ordValide.Id));
    }

    @isTest 
    static void TestGetAwsSetting(){
        AWS_Setting__mdt settings = MyDocsFileController.getAwsSetting();
    }
}