force-app/main/default/objects/Business_case__c/Business_case__c.object-meta.xml
<CustomObject>
    <label>Business case</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_case__c/fields/Ecran__c.field-meta.xml
<CustomField>
    <fullName>Ecran__c</fullName>
    <label>Ecran</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gouttiere</fullName>
            </value>
            <value>
                <fullName>Inlay core couronne</fullName>
            </value>
            <value>
                <fullName>Inlay onlay facette wax-up</fullName>
            </value>
            <value>
                <fullName>PEI, Cire</fullName>
            </value>
            <value>
                <fullName>Résine</fullName>
            </value>
            <value>
                <fullName>Stellite</fullName>
            </value>
            <value>
                <fullName>Implantologie</fullName>
            </value>
            <value>
                <fullName>Ortho</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Suprastructure</fullName>
            </value>
            <value>
                <fullName>Planification implantaire</fullName>
            </value>
            <value>
                <fullName>Couronne sur implant</fullName>
                <isActive>false</isActive>
                <label>Couronne sur implant</label>
            </value>
            <value>
                <fullName>Inlay onlay</fullName>
                <isActive>false</isActive>
                <label>Inlay onlay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Finition__c.field-meta.xml
<CustomField>
    <fullName>Finition__c</fullName>
    <label>Finition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sous_cran__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Finition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Materiau__c.field-meta.xml
<CustomField>
    <fullName>Materiau__c</fullName>
    <label>Matériau</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sous_cran__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CoCr</fullName>
            </value>
            <value>
                <fullName>NiCr</fullName>
            </value>
            <value>
                <fullName>Alliage précieux</fullName>
            </value>
            <value>
                <fullName>Alliage semi-précieux</fullName>
            </value>
            <value>
                <fullName>Composite</fullName>
            </value>
            <value>
                <fullName>Emax</fullName>
            </value>
            <value>
                <fullName>Full zircone</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Céramo zircone</fullName>
            </value>
            <value>
                <fullName>Wax-up</fullName>
            </value>
            <value>
                <fullName>ENAMIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Maximum__c.field-meta.xml
<CustomField>
    <fullName>Maximum__c</fullName>
    <inlineHelpText>Nombre maximum de dents pour appliquer cet élément</inlineHelpText>
    <label>Maximum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Minimum__c.field-meta.xml
<CustomField>
    <fullName>Minimum__c</fullName>
    <inlineHelpText>Nombre minimum de dents pour appliquer cet élément</inlineHelpText>
    <label>Minimum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <label>Produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Produit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Sous_cran__c.field-meta.xml
<CustomField>
    <fullName>Sous_cran__c</fullName>
    <label>Sous-écran</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Ecran__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gouttière</fullName>
            </value>
            <value>
                <fullName>PEI, Cire</fullName>
            </value>
            <value>
                <fullName>Résine</fullName>
            </value>
            <value>
                <fullName>Stellite</fullName>
            </value>
            <value>
                <fullName>Inlay onlay facette</fullName>
            </value>
            <value>
                <fullName>Projet esthétique</fullName>
            </value>
            <value>
                <fullName>Inlay core</fullName>
            </value>
            <value>
                <fullName>Couronne</fullName>
            </value>
            <value>
                <fullName>Couronne sur implant</fullName>
            </value>
            <value>
                <fullName>Pilier</fullName>
            </value>
            <value>
                <fullName>Ortho</fullName>
            </value>
            <value>
                <fullName>Réparations</fullName>
            </value>
            <value>
                <fullName>Appareil</fullName>
            </value>
            <value>
                <fullName>Barre</fullName>
            </value>
            <value>
                <fullName>Planification implantaire</fullName>
            </value>
            <value>
                <fullName>Implant</fullName>
                <isActive>false</isActive>
                <label>Implant</label>
            </value>
            <value>
                <fullName>Inlay onlay</fullName>
                <isActive>false</isActive>
                <label>Inlay onlay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_case__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sous_cran__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/Ligne__c.object-meta.xml
<CustomObject>
    <label>Ligne</label>
    <nameField>
        <displayFormat>{DD}-{MM}-{YYYY}-L{0}</displayFormat>
        <label>N°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne__c/fields/Finition__c.field-meta.xml
<CustomField>
    <fullName>Finition__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Facette&quot;,&quot;Finition directe&quot;,&quot;Inlay_core_couronne&quot;,&quot;Finition directe&quot;,&quot;Stellite&quot;,&quot;Finition directe&quot;,&quot;Resine&quot;,&quot;Finition directe&quot;,&quot;Inlay_onlay&quot;,&quot;Finition directe&quot;,&quot;ResineSansAffectation&quot;,&quot;Finition directe&quot;,&quot;Planification_implantaire&quot;,&quot;Planification implantaire et impression du guide&quot;,&quot;&quot;)</defaultValue>
    <label>Finition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Finition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/IsGouttiere__c.field-meta.xml
<CustomField>
    <fullName>IsGouttiere__c</fullName>
    <formula>RecordType.DeveloperName = &quot;Gouttiere&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsGouttiere</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/IsICC__c.field-meta.xml
<CustomField>
    <fullName>IsICC__c</fullName>
    <formula>RecordType.DeveloperName = &quot;Inlay_core_couronne&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsICC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <label>Produit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Produit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>Case($RecordType.DeveloperName,&quot;Facette&quot;,&quot;Céramique monolithique (hors zircone)&quot;,&quot;Inlay_core_couronne&quot;,&quot;Classique&quot;,&quot;Inlay_onlay&quot;,&quot;Composite&quot;,&quot;Resine&quot;,&quot;Résine standard&quot;,&quot;Wax_up&quot;,&quot;Wax-up&quot;,&quot;ResineSansAffectation&quot;,&quot;Résine standard&quot;,&quot;Planification_implantaire&quot;,&quot;Simplifié (pilot drill)&quot;,&quot;&quot;)</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ligne__c/fields/Validee__c.field-meta.xml
<CustomField>
    <fullName>Validee__c</fullName>
    <formula>Ordonnance__r.Je_valide_cette_commande_pour_envoi__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Validee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ligne__c/recordTypes/Gouttiere.recordType-meta.xml
<RecordType>
    <fullName>Gouttiere</fullName>
    <active>true</active>
    <label>Gouttière</label>
</RecordType>

force-app/main/default/objects/Ligne_de_commande__c/Ligne_de_commande__c.object-meta.xml
<CustomObject>
    <label>Ligne de commande</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de commande</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ligne_de_commande__c/fields/Business_case__c.field-meta.xml
<CustomField>
    <fullName>Business_case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business case</label>
    <referenceTo>Business_case__c</referenceTo>
    <relationshipLabel>Lignes de commande</relationshipLabel>
    <relationshipName>Lignes_de_commande</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Ligne__c.field-meta.xml
<CustomField>
    <fullName>Ligne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne</label>
    <referenceTo>Ligne__c</referenceTo>
    <relationshipLabel>Lignes de commande</relationshipLabel>
    <relationshipName>Lignes_de_commande</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ligne_de_commande__c/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lignes de commande</relationshipLabel>
    <relationshipName>Lignes_de_commande</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_de_facturation__c/Unit_de_facturation__c.object-meta.xml
<CustomObject>
    <label>Unité de facturation</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unités de facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_de_facturation__c/fields/Business_case__c.field-meta.xml
<CustomField>
    <fullName>Business_case__c</fullName>
    <label>Business case</label>
    <referenceTo>Business_case__c</referenceTo>
    <relationshipLabel>Unités de facturation</relationshipLabel>
    <relationshipName>Unit_s_de_facturation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PRG_LigneControllerExtension.cls
public class PRG_LigneControllerExtension {

    private final Ligne__c Ligne;
    public  List<Business_case__c> BCs;
    public  Map<Id,decimal> SelectedBCs;
    public List<Unit_de_facturation__c> Unites;
    public boolean readOnly {get;set;}
    
    public PRG_LigneControllerExtension(ApexPages.StandardController stdController) {
        this.Ligne = (Ligne__c)stdController.getRecord();
        readOnly = Ligne.Validee__c;
        SelectedBCs = new Map<Id,decimal>();
        if(Ligne.IsGouttiere__c){
	        BCs = [Select Id,Name,Ecran__c,Sous_cran__c,Type__c,Materiau__c,Options__c,Finition__c,Minimum__c,Maximum__c
	        		from Business_case__c where Ecran__c = 'Gouttiere'];
        }
        if(Ligne.IsICC__c){
	        BCs = [Select Id,Name,Ecran__c,Sous_cran__c,Type__c,Materiau__c,Options__c,Finition__c,Minimum__c,Maximum__c
	        		from Business_case__c where Ecran__c = 'Inlay core couronne'];
        }
        List<ID> listID = new List<ID>();
        for(Business_case__c BC:BCs){
        	listID.Add(BC.Id);
        }
        Unites = [Select Business_case__c,Produit__c from Unit_de_facturation__c where Business_case__c in :listID];
    }

    public PageReference SaveLigne(){
    	Ligne.En_cours_de_creation__c = false;
        if (getBusinessCases()){
	    	update Ligne;
	    	return Ordonnance(Ligne.Ordonnance__c);
        }else{
        	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Désolé, des informations sont manquantes, vous ne pouvez pas enregistrer cette ligne.'));
        	return null;
        }
    }
    
    public PageReference DeleteLigne(){
    	string IdOrd = Ligne.Ordonnance__c;
   		delete ligne;
    	return Ordonnance(IdOrd);
    }

    public PageReference CancelLigne(){
    	string IdOrd = Ligne.Ordonnance__c;
    	if (Ligne.En_cours_de_creation__c){
    		delete ligne;
    	}
    	return Ordonnance(IdOrd);
    }
    
    public PageReference Ordonnance(string IdOrdonnance){
    	Pagereference PR = new PageReference('/' + IdOrdonnance);
    	//PR.setRedirect(true);
    	return PR;
    }
    
/*    public PageReference Autosave() {
        update Ligne;
        getBusinessCases();
        return null;
    }

    public PageReference AutosaveArcade() {
        update Ligne;
        getBusinessCases();
        return null;
    }

    public PageReference AutosaveType() {
    	Ligne.Couronne__c = null;
        update Ligne;
        getBusinessCases();
        return null;
    }*/
    
    public boolean getBusinessCases(){
    	SelectedBCs.clear();
    	if(Ligne.IsGouttiere__c){
    		getBC('Gouttière',Ligne.Type__c,null,null,null,Ligne.Arcade__c =='Haut et bas'?2:1);
    	}
    	if(Ligne.IsICC__c){
    		system.debug('Vue ' + Ligne.Inlay_core__c + '-' + Ligne.Dents_a_restorer__c);
    		List<Temp__c> tmp = [Select Valeur__c from Temp__c where Info__c =: (string)Ligne.Id + 'Inlay_core__c'];
    		if (tmp.size()==1){
		        Ligne.Inlay_core__c = '';
        		Object[] values = (Object[])System.JSON.deserializeUntyped(tmp[0].Valeur__c);
        		if(values.size()>0){
            		Ligne.Inlay_core__c = String.join(values, ';');
            		Ligne.txtInlayCore__c = Ligne.Inlay_core__c;
        		}
    		}
    		tmp = [Select Valeur__c from Temp__c where Info__c =: (string)Ligne.Id + 'Dents_a_restorer__c'];
    		if (tmp.size()==1){
		        Ligne.Dents_a_restorer__c = '';
        		Object[] values = (Object[])System.JSON.deserializeUntyped(tmp[0].Valeur__c);
        		if(values.size()>0){
            		Ligne.Dents_a_restorer__c = String.join(values, ';');
            		Ligne.txtDents__c = Ligne.Dents_a_restorer__c;
        		}
    		}
    		getBC('Couronne',Ligne.Couronne__c,Ligne.Alliage__c,null,Ligne.Finition__c,(string.isblank(Ligne.Inlay_core__c))?0:Ligne.Inlay_core__c.split(';').size());
    		getBC('Inlay core',Ligne.Type__c,Ligne.Alliage_Inlay_core__c,null,Ligne.Finition__c,(string.isblank(Ligne.Dents_a_restorer__c))?0:Ligne.Dents_a_restorer__c.split(';').size());
    	}
    	List<Ligne_de_commande__c> oldLCs = [Select Id from Ligne_de_commande__c where Ligne__c = :Ligne.Id];
    	if(oldLCs.size()>0){
    		delete oldLCS;
    	}
    	List<Ligne_de_commande__c> LCs = new List<Ligne_de_commande__c>();
   		boolean trouve = false;
    	for (String BCid : SelectedBCs.keySet()){
    		for(Unit_de_facturation__c Unite:Unites){
	   			if(Unite.Business_case__c == BCId){
	   				trouve = true;
					Ligne_de_commande__c LC = new Ligne_de_commande__c();
					LC.Ligne__c = Ligne.Id;
            		LC.Business_case__c = BCid;
            		LC.Quantite__c = SelectedBCs.get(BCId);
            		LC.Ordonnance__c = Ligne.Ordonnance__c;
            		LC.Produit__c = Unite.Produit__c;
            		LCs.Add(LC);
    			}
    		}
/*    		if (!trouve){
				Ligne_de_commande__c LC = new Ligne_de_commande__c();
				LC.Ligne__c = Ligne.Id;
           		LC.Business_case__c = BCid;
           		LC.Quantite__c = SelectedBCs.get(BCId);
           		LC.Ordonnance__c = Ligne.Ordonnance__c;
           		LCs.Add(LC);
    		}*/
        }
    	if(LCs.size()>0){
    		insert LCs;
    	}
    	return (trouve);
    }
    
    public void getBC(string SousEcran,string Type,string Materiau,string Options, string Finition, integer nb){
    	for(Business_case__c BC:BCs){
    		if(isOK(BC.Sous_cran__c,SousEcran)){
	    		if(isOK(BC.Type__c,Type)){
		    		if(isOK(BC.Materiau__c,Materiau)){
			    		if(isOK(BC.Options__c,Options)){
				    		if(isOK(BC.Finition__c,Finition)){
				    			if((BC.Minimum__c>=0)&&(BC.Maximum__c>=0)){
				    				if ((nb>=BC.Minimum__c) && (nb<=BC.Maximum__c)){
				    					SelectedBCs.put(BC.Id,1);
				    				} 
				    			}else{
				    				SelectedBCs.put(BC.Id,nb);
				    			}
			    			}
		    			}
	    			}
    			}
    		}
    	}
    }
    
    public boolean isOK(string s1,string s2){ 
    	if(string.isblank(s2)){
    		return true;
    	}else{
    		if(string.isblank(s1)){
    			return false;
    		}else{
    			return (s1 == s2);
    		}
    	}
    }
}